include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_relative_imports: true
    prefer_expression_function_bodies: true

analyzer:
  exclude:
    # Tests
    - "test/**.mocks.dart"
    - ".test_coverage.dart"
    # Assets
    - "assets/**"

  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

  # Enable the following options to enable strong mode.
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
